 ADDING ENCRIPTION TO A FUNCTION OR STORE PROCEDURE: JUST WRITE 'WITH ENCRYPTION' AFTER 'RETURNS


ALTER FUNCTION InlineTableFunction()
RETURNS TABLE 
WITH ENCRYPTION 
AS
RETURN(select name, Age from tblPersons)

-- NOW LET4S TRY TO VIEW THE FUNCTION BY USING 'sp_helptext'

sp_helptext  InlineTableFunction